### PR TITLE
V7.0

### PR DESCRIPTION
**Pull request by Spomky**

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
@Spomky So no breaking functionality change, just the PHP version bump and lots of cleanup?

**Comment by Spomky** [comment]
Hi @moderndeveloperllc 

Good catch!
I previously created a v7 branch but there was too much changes. Not only BC Breaks but all classes/features were reviewed so I decided to create a brand new project to handle that.

So this `v7` for this project is a simple update to allow the use of the library on PHP7.2+ projects.
In the meantime it drops PHP5.6 (security fixes only) and HHVM (I have troubles with extensions).

You will find the new project in [a dedicated organization](https://github.com/web-token/).
This organization handles 
* [the framework itself](https://github.com/web-token/jwt-framework): a monolithic repository that contains all the features.
* [a standalone application](https://github.com/web-token/jwt-app) for key management (conversion, rotation...).
* [the documentation](https://github.com/web-token/jwt-doc)

I split the framework and sync it with many repositories (all othat `jwt-*` repositories). This way you will just install the features you need (e.g. you only need the encryption bundle for your Symfony application).

I have just started to write the documentation. Please see https://web-token.spomky-labs.com if you want to read the first chapters.
Hope you will enjoy that new project. Sorry for the lack of communication, I would like to finish the documentation before.

**Comment by moderndeveloperllc** [comment]
@Spomky No problem. Glad you still like sinking your teeth into such a large project! I guess when that is up and running, this repo will go into maintenance mode? You might want to explicitly set v7 to be something like an "LTS" where only security updates are done for a set amount of time (probably won't be any/many honestly) and then provide some upgrade docs to the new project. I'll be sure to star that one to see when it goes at least beta.

**Comment by Spomky** [comment]
Hi @moderndeveloperllc,

This library will be maintained during approx. 2 years (see #297) for security fixes.

There are lot of differences between this library and the new project so it will not be easy to provide an upgrade documentation. However If you think it is useful then I will try to write some Before/After pages.

**Pull request merged**
