### PR TITLE
Private keys from APN support

### LINKED ISSUE #141: Generate JWT for Apple Push Notification
I want to use `jose` library for generating JWT for Apple Push Notification.
But I don't know what implementation (JWT, JWS, JWE, JWA, JWK or JWKSet) I should use.
There are some [requirements](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html) for generating this token:
1) Headers should be:
```json
{
    "alg": "ES256",
    "kid": "ABC123DEFG"
}
```
2) Payload data should be:
```json
{
    "iss": "DEF123GHIJ",
    "iat": 1437179036
 }
```
3) APNs supports only provider authentication tokens that are signed with the ES256 algorithm.

So could you please provide an example of generating JWT token for Apple Push Notifications with you library?

### PR DESCRIPTION
**Pull request by Spomky**
This PR fixes #141 

The keys  generated by the Apple Push Notification Service are not correctly loaded by the JWKFactory and the EC key converter.
It seems that the problem comes from the way the keys are encoded.
As per the [ASN.1 parser](https://lapo.it/asn1js/#308193020100301306072A8648CE3D020106082A8648CE3D030107047930770201010420D779F78AC7EC124B7397E0AD1F9102A51ACA93EE34A6B56E09B95D90FEFB81A9A00A06082A8648CE3D030107A1440342000461C20C5246A5C1B79E01591417A14FDDA055942CE5AB111DEE2D2E37FE2BA00D6D4F30396241913359EB5801D7FE31A7EAFCFAE56C401F03E97B25F9A28C0B2F), the sequence that holds the information is wrapped into another sequence. This sequence comes from the [RFC5208](https://tools.ietf.org/html/rfc5208).

At the moment, this PR fixes the bug. A test has been added.
However the key converter should be updated to be fully compliant with the [RFC5915](https://tools.ietf.org/html/rfc5915) and [RFC5208](https://tools.ietf.org/html/rfc5208).

* [x] Load keys from APN (see [RFC5208](https://tools.ietf.org/html/rfc5208))
* [x] Fix loading with older OpenSSL versions whern linebreaks after 64 chars are not set.

### CODE REVIEW

**Comment by Spomky** [comment]
@edamov could you please verify the key is correctly loaded with by this PR?

**Comment by edamov** [comment]
It works!

**Comment by Spomky** [comment]
Thanks. It seems I introduced a new bug (a test failed on that PR).
I will fix it then I'll merge and tag by the end of the day.

**Comment by Spomky** [comment]
Merged and tagged as `v6.1.1`.

Thanks again

**Pull request merged**
